; Exercise 1.9.  Each of the following two procedures defines a method for adding two positive 
; integers in terms of the procedures inc, which increments its argument by 1, and dec,
; which decrements its argument by 1.

; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). 
; Are these processes iterative or recursive?

;(define (inc x) (+ x 1))
;(define (dec x) (- x 1))

;(define (+ a b)
;  (if (= a 0)
;      b
;      (inc (+ (dec a) b))))


;(+ 4 5)
; (inc (+ (dec 4) 5))
; (inc (+ (3) 5))
; (inc (8))
;9
; recursive because inc is called 3 times. 




;(define (+ a b)
;  (if (= a 0)
;      b
;      (+ (dec a) (inc b))))


;(+ 4 5)
;(+ (dec 4) (inc 5))
;(+ (3) (6))
;9
; iterative because the variables state is returned from dec and inc and then added. (state passed)

